[project]
name = "discord-bot-mts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gridfs>=0.0.1",
    "py-cord[voice]>=2.6.1",
    "pydub>=0.25.1",
    "pymongo[srv]==3.12",
    "python-dotenv>=1.1.0",
]
